### ISSUE TITLE
Background transparency

### ISSUE THREAD

**Issue by mstanciu552** [yong1le/darkplus.nvim#1]
Love the theme, but if I want transparency it only works until the end of the file not the entire screen...

![Screenshot_20210722_213534](https://user-images.githubusercontent.com/34579048/126691224-ae608fa7-b996-42c2-bf91-6876043c988c.png)

Is there anything that can be done?

**Comment by yong1le** [comment]
Hi @mstanciu552,
What settings are you using to set the transparency? It works fine for me when I put these lines in my config.
``` lua
-- Highlights to be transparent
vim.cmd('au ColorScheme * hi Normal ctermbg=NONE guibg=NONE')
vim.cmd('au ColorScheme * hi NonText ctermbg=NONE guibg=NONE')

vim.cmd [[colorscheme darkplus]]

```
![Screenshot 2021-07-22 153513](https://user-images.githubusercontent.com/76537485/126699073-3bd66a91-af9b-4a2e-a725-14633d033d8b.png)

**Comment by yong1le** [comment]
I have removed the background colour of the EndOfBuffer highlight group in c6aedfca4666a0752b3bd649ef1cfab17b94d779 . It should work now.

**Comment by mstanciu552** [comment]
Yes, perfect. Thanks for the fast response!

Closing the issue now.
